### ISSUE TITLE
Does this tool allow for control or simply to view status?

### ISSUE THREAD

**Issue by rohankapoorcom** [Loafdude/xapman#2]
I've managed to get xapman to connect to my MQTT server and XAP800 units (2 of them). it's connected to the second unit because the first one is directly connected to the machine running G-Ware. All of the data seems to populate correctly into MQTT but changing any of the topics does not trigger any change on the XAP units themselves. Is that intended behavior?

**Comment by Loafdude** [comment]
You can control nearly every aspect via MQTT. I tried to implement the entire serial protocol.
In the XAP800 manual use the serial reference to see which commands are available you may want to use
You can find them defined in the sourcecode.

I actually find it easier to have an MQTT client subscribed to "Home/Audio/#" (but I recommend only starting the sub after the xapman software finishes start up because it dumps all variables to MQTT which is huge)
Then change a value in G-Ware and you will see the corresponding message in your MQTT client. You can then use that to get nearly the correct topic (minus the command you would like to run)

Here are some examples

Ramp Gain Value:
topic: "Home/Audio/GreatMatrix/Outputs/LvRm Front Right/rampToDb"
payload: "[-8]"
Which runs the command "rampToDb" on matrix named "GreatMatrix" on channel named "LvRm Front Right" to a value of -8

Mute Channel:
topic: "Home/Audio/GreatMatrix/Outputs/LvRm Front Right/setMute"
payload: "[1]"

Matrix link / unlink:
topic: "Home/Audio/GreatMatrix/Matrix/Src:House Left(Y)/Dest:LvRm Proc Left(A)/linkChannels"
payload: "[]"
topic: "Home/Audio/GreatMatrix/Matrix/Src:House Left(Y)/Dest:LvRm Proc Left(A)/unlinkChannels"
payload: "[]"

Change Volume (Attenuation actually) on Matrix Link to -2
topic: "Home/Audio/GreatMatrix/Matrix/Src:House Left(Y)/Dest:LvRm Pro Sub(C)/setAttenuation"
payload: "[-2]"
